---
config: "~/.ansible/collections/ansible_collections/hpe/oneview/roles/REI_isse/files/oneview_config.json"
ov_template:  SPT-test
sp_name: SP-1
server_profile_description: Test SP
enclosure_group_name: EG
server_hardware_type_name: SY 480 Gen10 1
network_name: mgmt_nw
